pub const CENTROS: [(char,&str); 26] = [
    ('3',"3 - C. U. DE TLAJOMULCO"),
    ('A',"A - C.U. DE ARTE, ARQ. Y DISEÑO"),
    ('B',"B - C.U. DE CS. BIOLOGICO Y AGR."),
    ('C',"C - C.U. DE CS. ECONOMICO-ADMVAS."),
    ('D',"D - C.U. DE CS. EXACTAS E ING."),
    ('E',"E - C.U. DE CS. DE LA SALUD"),
    ('F',"F - C.U. DE CS. SOCIALES Y HUM."),
    ('G',"G - C.U. DE LOS ALTOS"),
    ('H',"H - C.U. DE LA CIENEGA"),
    ('I',"I - C.U. DE LA COSTA"),
    ('J',"J - C.U. DE LA COSTA SUR"),
    ('K',"K - C.U. DEL SUR"),
    ('M',"M - C. U. DE LOS VALLES"),
    ('N',"N - C.U. DEL NORTE"),
    ('O',"O - CUCEI SEDE VALLES"),
    ('P',"P - CUCSUR SEDE VALLES"),
    ('Q',"Q - CUCEI SEDE NORTE"),
    ('R',"R - CUALTOS SEDE NORTE"),
    ('S',"S - CUCOSTA SEDE NORTE"),
    ('T',"T - SEDE TLAJOMULCO"),
    ('U',"U - C. U. DE LOS LAGOS"),
    ('V',"V - CICLO DE VERANO"),
    ('W',"W - CUCEA SEDE VALLE"),
    ('X',"X - SIST. DE UNIVERSIDAD VIRTUAL"),
    ('Y',"Y - ESCUELAS INCORPORADAS"),
    ('Z',"Z - C. U. DE TONALA")
];